"""
PyOS NOVA — VM Runner
======================
Boots PyOS NOVA in a QEMU virtual machine using UEFI firmware (OVMF).
No Linux kernel. No Syslinux. No bootloader software.

The boot chain:
  QEMU (hardware emulator)
    → OVMF firmware (UEFI, open-source, Apache-2.0 license)
    → EFI/BOOT/BOOTX64.EFI  ← generated by efi_builder.py
    → Python
    → NOVA kernel + shell

OVMF replaces the physical UEFI chip present in real hardware.
This lets you test NOVA on any machine before flashing to USB.

Usage:
  python3 nova_vm.py              # auto-build EFI + launch VM
  python3 nova_vm.py --install    # install QEMU + OVMF via pip helper
  python3 nova_vm.py --img SIZE   # create disk image of SIZE MB (default 512)
"""

import os
import sys
import shutil
import struct
import subprocess
import tempfile
import argparse
import urllib.request
from pathlib import Path

ROOT     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD    = os.path.join(ROOT, "build")
DATA     = os.environ.get("NOVA_DATA", os.path.expanduser("~/.nova"))
IMG_PATH = os.path.join(BUILD, "nova.img")

# OVMF firmware (UEFI for QEMU) — Apache 2.0 licensed
# Available in most Linux package managers as ovmf / edk2-ovmf
OVMF_SEARCH_PATHS = [
    "/usr/share/OVMF/OVMF_CODE.fd",
    "/usr/share/ovmf/OVMF.fd",
    "/usr/share/edk2-ovmf/OVMF_CODE.fd",
    "/usr/share/qemu/OVMF.fd",
    "/opt/homebrew/share/qemu/edk2-x86_64-code.fd",
    os.path.expanduser("~/.nova/OVMF.fd"),
    os.path.join(BUILD, "OVMF.fd"),
]

OVMF_DOWNLOAD_URL = (
    "https://github.com/retrage/edk2-nightly/releases/download/"
    "v0.0.1/RELEASEX64_OVMF_CODE.fd"
)


# ─────────────────────────────────────────────────────────────────────────────
# OVMF / QEMU detection
# ─────────────────────────────────────────────────────────────────────────────

def find_ovmf() -> Optional[str]:
    """Find and return ovmf.


        Returns:
            Optional[str]: Result.
        """
    for p in OVMF_SEARCH_PATHS:
        if os.path.exists(p):
            return p
    return None


def find_qemu() -> Optional[str]:
    """Find and return qemu.


        Returns:
            Optional[str]: Result.
        """
    for name in ("qemu-system-x86_64", "qemu-system-x86_64.exe"):
        path = shutil.which(name)
        if path:
            return path
    return None


def download_ovmf(dest: str = None) -> str:
    """Download ovmf to local storage.

        Args:
        dest (str): Dest, defaults to None.


        Returns:
            str: Result.
        """
    dest = dest or os.path.join(BUILD, "OVMF.fd")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    if os.path.exists(dest):
        return dest
    print(f"  Downloading OVMF firmware (~3MB)...")
    print(f"  URL: {OVMF_DOWNLOAD_URL}")

    def progress(block, block_size, total):
        """Progress.

            Args:
            block: Block.
            block_size: Block size.
            total: Total.
            """
        if total > 0:
            pct = block * block_size / total * 100
            print(f"\r  {min(pct, 100):.0f}%  ", end="", flush=True)

    urllib.request.urlretrieve(OVMF_DOWNLOAD_URL, dest, reporthook=progress)
    print(f"\r  Downloaded: {dest} ({os.path.getsize(dest)//1024} KB)")
    return dest


# ─────────────────────────────────────────────────────────────────────────────
# FAT32 disk image builder (pure Python)
# Creates a bootable FAT32 image with BOOTX64.EFI and Nova source
# ─────────────────────────────────────────────────────────────────────────────

class FAT32Builder:
    """
    Pure Python FAT32 disk image builder.
    Enough to create a bootable UEFI USB image without mkfs.fat or dosfstools.

    Implements the essential FAT32 structures:
      - MBR with GPT partition table
      - FAT32 boot sector (BPB)
      - FAT tables (FAT1 + FAT2)
      - Root directory entries
      - File data clusters
    """

    SECTOR_SIZE      = 512
    CLUSTER_SIZE     = 4096  # 8 sectors per cluster
    SECTORS_PER_CLUSTER = CLUSTER_SIZE // SECTOR_SIZE
    RESERVED_SECTORS = 32    # Boot sector + FSInfo + backup
    FAT_COUNT        = 2
    ROOT_ENTRIES     = 0     # 0 = FAT32 (root dir in cluster chain)
    MEDIA_DESCRIPTOR = 0xF8  # Fixed disk

    FAT_EOC = 0x0FFFFFFF     # End of cluster chain marker

    def __init__(self, size_mb: int = 64):
        """Initialise the instance."""
        self.size_mb      = size_mb
        self.total_sectors = (size_mb * 1024 * 1024) // self.SECTOR_SIZE
        # FAT size calculation
        self.sectors_per_fat = self._calc_fat_size()
        self.first_data_sector = (
            self.RESERVED_SECTORS
            + self.FAT_COUNT * self.sectors_per_fat
        )
        self.total_clusters = (
            (self.total_sectors - self.first_data_sector)
            // self.SECTORS_PER_CLUSTER
        )
        self._fat    = [0] * (self.total_clusters + 2)
        self._fat[0] = 0x0FFFFFF8   # Media descriptor
        self._fat[1] = 0x0FFFFFFF   # End-of-chain
        self._next_cluster = 2
        self._files: dict = {}       # path → (cluster, data_bytes)
        self._dirs:  set  = set()

    def _calc_fat_size(self) -> int:
        # FAT32: each cluster needs 4 bytes in FAT table
        """Calc fat size.


            Returns:
                int: Result.
            """
        data_sectors   = self.total_sectors - self.RESERVED_SECTORS
        # Iterative: fat_sectors * FAT_COUNT contributes to non-data area
        fat_sectors = max(
            1,
            (data_sectors * 4 + self.SECTOR_SIZE - 1) // self.SECTOR_SIZE
        )
        return fat_sectors

    def add_dir(self, path: str):
        """Register a directory path."""
        self._dirs.add(path.upper().replace("/", "\\"))

    def add_file(self, path: str, data: bytes):
        """Add a file at `path` with content `data`."""
        # Allocate clusters
        if not data:
            self._files[path.upper()] = (self.FAT_EOC, b"")
            return
        clusters_needed = (len(data) + self.CLUSTER_SIZE - 1) // self.CLUSTER_SIZE
        start_cluster = self._alloc_clusters(clusters_needed)
        self._files[path.upper()] = (start_cluster, data)

    def _alloc_clusters(self, n: int) -> int:
        """Alloc clusters.

            Args:
            n (int): N.


            Returns:
                int: Result.
            """
        start = self._next_cluster
        for i in range(n):
            c = self._next_cluster
            self._next_cluster += 1
            if i < n - 1:
                self._fat[c] = c + 1
            else:
                self._fat[c] = self.FAT_EOC
        return start

    def _cluster_to_sector(self, cluster: int) -> int:
        """Cluster to sector.

            Args:
            cluster (int): Cluster.


            Returns:
                int: Result.
            """
        return self.first_data_sector + (cluster - 2) * self.SECTORS_PER_CLUSTER

    def build(self) -> bytes:
        """Assemble the complete FAT32 disk image."""
        img = bytearray(self.total_sectors * self.SECTOR_SIZE)

        # ── Boot Sector (sector 0) ─────────────────────────────────────────────
        bs = self._build_boot_sector()
        img[0:512] = bs

        # ── FSInfo sector (sector 1) ───────────────────────────────────────────
        fsi = self._build_fsinfo()
        img[512:1024] = fsi

        # ── FAT table(s) ──────────────────────────────────────────────────────
        fat_bytes = b"".join(struct.pack("<I", v) for v in self._fat)
        fat_sector_start = self.RESERVED_SECTORS
        for fat_num in range(self.FAT_COUNT):
            offset = (fat_sector_start + fat_num * self.sectors_per_fat) * self.SECTOR_SIZE
            img[offset:offset + len(fat_bytes)] = fat_bytes

        # ── Root directory (cluster 2) ─────────────────────────────────────────
        root_cluster   = 2
        root_data      = self._build_root_directory()
        root_sector    = self._cluster_to_sector(root_cluster) * self.SECTOR_SIZE
        img[root_sector:root_sector + len(root_data)] = root_data

        # ── File data ─────────────────────────────────────────────────────────
        for path_upper, (start_cluster, data) in self._files.items():
            if not data:
                continue
            cluster   = start_cluster
            data_view = memoryview(data)
            offset    = 0
            while offset < len(data):
                sector = self._cluster_to_sector(cluster)
                chunk  = bytes(data_view[offset:offset + self.CLUSTER_SIZE])
                chunk += b"\x00" * (self.CLUSTER_SIZE - len(chunk))   # pad
                img[sector * self.SECTOR_SIZE:(sector + 1) * self.SECTOR_SIZE * self.SECTORS_PER_CLUSTER] = chunk
                offset += self.CLUSTER_SIZE
                cluster = self._fat[cluster]
                if cluster >= self.FAT_EOC:
                    break

        return bytes(img)

    def _build_boot_sector(self) -> bytes:
        """FAT32 Boot Parameter Block (BPB)."""
        bs  = bytearray(512)
        # Jump to boot code + NOP
        bs[0:3] = b"\xEB\x58\x90"
        # OEM Name
        bs[3:11] = b"MSWIN4.1"
        # BPB
        struct.pack_into("<H",  bs, 11, self.SECTOR_SIZE)         # BytesPerSector
        struct.pack_into("<B",  bs, 13, self.SECTORS_PER_CLUSTER) # SectorsPerCluster
        struct.pack_into("<H",  bs, 14, self.RESERVED_SECTORS)    # ReservedSectors
        struct.pack_into("<B",  bs, 16, self.FAT_COUNT)            # NumFATs
        struct.pack_into("<H",  bs, 17, self.ROOT_ENTRIES)         # RootEntryCount (0 for FAT32)
        struct.pack_into("<H",  bs, 19, 0)                         # TotalSectors16 (0 = use 32)
        struct.pack_into("<B",  bs, 21, self.MEDIA_DESCRIPTOR)     # Media
        struct.pack_into("<H",  bs, 22, 0)                         # SectorsPerFAT16 (0 = FAT32)
        struct.pack_into("<H",  bs, 24, 63)                        # SectorsPerTrack
        struct.pack_into("<H",  bs, 26, 255)                       # NumHeads
        struct.pack_into("<I",  bs, 28, 0)                         # HiddenSectors
        struct.pack_into("<I",  bs, 32, self.total_sectors)        # TotalSectors32
        # FAT32 Extended BPB
        struct.pack_into("<I",  bs, 36, self.sectors_per_fat)      # SectorsPerFAT32
        struct.pack_into("<H",  bs, 40, 0)                         # ExtFlags
        struct.pack_into("<H",  bs, 42, 0)                         # FSVersion
        struct.pack_into("<I",  bs, 44, 2)                         # RootCluster (cluster 2)
        struct.pack_into("<H",  bs, 48, 1)                         # FSInfoSector
        struct.pack_into("<H",  bs, 50, 6)                         # BackupBootSector
        struct.pack_into("<B",  bs, 64, 0x80)                      # DriveNumber
        struct.pack_into("<B",  bs, 65, 0)                         # Reserved1
        struct.pack_into("<B",  bs, 66, 0x29)                      # BootSignature
        struct.pack_into("<I",  bs, 67, 0xDEADBEEF)               # VolumeID
        bs[71:82] = b"NOVA       "                                  # VolumeLabel
        bs[82:90] = b"FAT32   "                                     # FSType
        # Boot sector signature
        bs[510] = 0x55
        bs[511] = 0xAA
        return bytes(bs)

    def _build_fsinfo(self) -> bytes:
        """Build and return fsinfo.


            Returns:
                bytes: Result.
            """
        fsi = bytearray(512)
        struct.pack_into("<I", fsi, 0,   0x41615252)  # LeadSig
        struct.pack_into("<I", fsi, 484, 0x61417272)  # StrucSig
        struct.pack_into("<I", fsi, 488, 0xFFFFFFFF)  # FreeCount (unknown)
        struct.pack_into("<I", fsi, 492, 0xFFFFFFFF)  # NextFree (unknown)
        struct.pack_into("<I", fsi, 508, 0xAA550000)  # TrailSig
        return bytes(fsi)

    def _build_root_directory(self) -> bytes:
        """Build root directory entries for all registered files."""
        entries = bytearray()

        # Volume label entry
        vol = bytearray(32)
        vol[0:11] = b"NOVA       "
        vol[11]   = 0x08    # ATTR_VOLUME_ID
        entries += vol

        # File/directory entries
        for path_upper, (start_cluster, data) in self._files.items():
            parts = path_upper.strip("\\").split("\\")
            if len(parts) != 1:
                continue    # subdirectory — skip for now (simplified)
            name = parts[0]
            entry = self._dir_entry(name, start_cluster, len(data), is_dir=False)
            entries += entry

        # Pad to cluster size
        entries += b"\x00" * (self.CLUSTER_SIZE - len(entries) % self.CLUSTER_SIZE)
        return bytes(entries)

    def _dir_entry(self, name83: str, cluster: int,
                   size: int, is_dir: bool = False) -> bytes:
        """Build a FAT 8.3 directory entry."""
        entry = bytearray(32)
        # Convert name to 8.3 format
        if "." in name83:
            n, e = name83.rsplit(".", 1)
        else:
            n, e = name83, ""
        name_bytes = (n[:8].ljust(8) + e[:3].ljust(3)).encode("ascii", errors="replace")
        entry[0:11] = name_bytes[:11]
        entry[11]   = 0x10 if is_dir else 0x20    # Attributes
        entry[26]   = cluster & 0xFF              # ClusterLow lo
        entry[27]   = (cluster >> 8) & 0xFF       # ClusterLow hi
        entry[20]   = (cluster >> 16) & 0xFF      # ClusterHigh lo
        entry[21]   = (cluster >> 24) & 0xFF      # ClusterHigh hi
        struct.pack_into("<I", entry, 28, size)   # FileSize
        return bytes(entry)


# ─────────────────────────────────────────────────────────────────────────────
# Build + launch
# ─────────────────────────────────────────────────────────────────────────────

def build_image(size_mb: int = 128) -> str:
    """Build a bootable FAT32 disk image with NOVA EFI."""
    os.makedirs(BUILD, exist_ok=True)

    # Generate BOOTX64.EFI
    from boot.efi_builder import build_efi
    efi_path = os.path.join(BUILD, "BOOTX64.EFI")
    print("  Building BOOTX64.EFI...")
    build_efi(efi_path, verify=True)
    efi_data = open(efi_path, "rb").read()
    print(f"  EFI: {len(efi_data)} bytes")

    # Collect NOVA source files
    print("  Collecting NOVA source...")
    nova_files = {}
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in ("__pycache__", ".git", "build", ".nova")]
        for fname in filenames:
            if fname.endswith((".py", ".md", ".txt", ".sh", ".json")):
                full = os.path.join(dirpath, fname)
                rel  = os.path.relpath(full, ROOT)
                nova_files[rel] = open(full, "rb").read()

    # Build FAT32 image
    print(f"  Building {size_mb}MB FAT32 image...")
    fat = FAT32Builder(size_mb=size_mb)
    fat.add_file("EFI\\BOOT\\BOOTX64.EFI", efi_data)
    for rel, data in nova_files.items():
        fat_path = "NOVA\\" + rel.replace("/", "\\").replace("..", "__")
        fat.add_file(fat_path, data)

    img_data = fat.build()
    with open(IMG_PATH, "wb") as f:
        f.write(img_data)
    print(f"  Image: {IMG_PATH} ({os.path.getsize(IMG_PATH)//1024//1024} MB)")
    return IMG_PATH


def launch_qemu(img_path: str, ovmf_path: str, memory_mb: int = 512,
                gui: bool = True):
    """Launch QEMU with UEFI firmware booting our image."""
    qemu = find_qemu()
    if not qemu:
        print("  QEMU not found. Install it:")
        print("    Linux  : sudo apt install qemu-system-x86")
        print("    macOS  : brew install qemu")
        print("    Windows: https://www.qemu.org/download/")
        sys.exit(1)

    cmd = [
        qemu,
        "-m",       str(memory_mb),
        "-drive",   f"if=pflash,format=raw,readonly=on,file={ovmf_path}",
        "-drive",   f"format=raw,file={img_path}",
        "-net",     "none",
    ]
    if not gui:
        cmd += ["-nographic", "-serial", "stdio"]
    else:
        cmd += ["-vga", "std"]

    print(f"\n  Launching QEMU...")
    print(f"  Command: {' '.join(cmd)}\n")
    print("  " + "─" * 60)
    subprocess.run(cmd)


def install_deps():
    """Help the user install QEMU and OVMF."""
    print("  Installing dependencies...\n")
    import platform
    sys_  = platform.system()
    if sys_ == "Linux":
        pkg = "qemu-system-x86 ovmf"
        print(f"  Run: sudo apt install {pkg}")
        print(f"  Or:  sudo dnf install qemu-system-x86_64 edk2-ovmf")
        print(f"  Or:  sudo pacman -S qemu ovmf")
    elif sys_ == "Darwin":
        print("  Run: brew install qemu")
        print("  OVMF is bundled with QEMU on macOS (homebrew)")
    else:
        print("  Windows: download QEMU from https://qemu.org/download/")
        print("  OVMF:    download from https://github.com/tianocore/edk2")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="PyOS NOVA VM Runner (UEFI, no kernel)")
    ap.add_argument("--img",      type=int, default=128,   metavar="MB",  help="Disk image size in MB")
    ap.add_argument("--ram",      type=int, default=512,   metavar="MB",  help="VM RAM in MB")
    ap.add_argument("--nographic", action="store_true",                    help="Text-only mode")
    ap.add_argument("--install",   action="store_true",                    help="Show installation instructions")
    ap.add_argument("--build-only",action="store_true",                    help="Build image only, don't launch")
    args = ap.parse_args()

    if args.install:
        install_deps()
        sys.exit(0)

    print("\n  PyOS NOVA — VM Runner")
    print("  ─────────────────────────────────────────────────────────")
    print("  Boot chain: QEMU → OVMF (UEFI) → BOOTX64.EFI → Python")
    print("  No Linux kernel. No Syslinux. No Alpine. Just UEFI + Python.\n")

    img = build_image(args.img)

    if args.build_only:
        print(f"\n  Image ready: {img}")
        print(f"  Flash to USB: sudo dd if={img} of=/dev/sdX bs=4M status=progress")
        sys.exit(0)

    # Find or download OVMF
    ovmf = find_ovmf()
    if not ovmf:
        print("  OVMF firmware not found locally.")
        ans = input("  Download OVMF (~3MB)? [Y/n] ").strip().lower()
        if ans in ("", "y", "yes"):
            ovmf = download_ovmf()
        else:
            print("  Install OVMF manually (see --install) or run on real UEFI hardware.")
            sys.exit(1)

    print(f"  OVMF: {ovmf}")
    launch_qemu(img, ovmf, memory_mb=args.ram, gui=not args.nographic)
